[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/rShetty/asyncwait"
